deploy weblogic with buildpack

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,26 +1,67 @@
-#!/usr/bin/env ruby
-# Encoding: utf-8
-# Cloud Foundry Java Buildpack
-# Copyright (c) 2013 the original author or authors.
-#
-# Licensed under the Apache License, Version 2.0 (the "License");
-# you may not use this file except in compliance with the License.
-# You may obtain a copy of the License at
-#
-#      http://www.apache.org/licenses/LICENSE-2.0
-#
-# Unless required by applicable law or agreed to in writing, software
-# distributed under the License is distributed on an "AS IS" BASIS,
-# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-# See the License for the specific language governing permissions and
-# limitations under the License.
+#!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir>
 
-$stdout.sync = true
-$stderr.sync = true
-$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
+# important directories: https://gist.github.com/fe7f04abbd9538b656c5
+# COMPILE_BUILDPACK_DIR，获取buildpack脚本所在的目录 https://github.com/tchenData/container-info-buildpack
+BUILD_DIR=$1
+CACHE_DIR=$2 
+COMPILE_BUILDPACK_DIR=$(cd $(dirname $0) && cd .. && pwd)
 
-require 'java_buildpack/buildpack'
+# fail fast
+set -e
 
-build_dir = ARGV[0]
+# NOTE: the rest of this script assumes that we're in the cache directory
+if [ ! -d "${CACHE_DIR}/Oracle/software" ]; then
+  mkdir -p $CACHE_DIR/Oracle/software
+fi
 
-JavaBuildpack::Buildpack.drive_buildpack_with_logger(build_dir, 'Compile failed with exception %s') { |buildpack| buildpack.compile }
+cd ${CACHE_DIR}
+
+ln -s "${CACHE_DIR}" /app
+
+# install bea jrockit jdk
+JROCKIT_JDK_FILE=jrockit-jdk1.6.0_20-R28.1.0-4.0.1-linux-x64.bin
+JROCKIT_JDK_URL="http://192.168.2.103:8001/buildpack/jdk/jrockit-jdk1.6.0_20-R28.1.0-4.0.1-linux-x64.bin"
+if [ ! -d "${CACHE_DIR}/Oracle/jrockit-jdk1.6.0_20" ]; then
+  mkdir -p $CACHE_DIR/Oracle/jrockit-jdk1.6.0_20
+  echo -n "-----> Installing jrockit jdk ${JROCKIT_JDK_FILE}..."
+  wget $JROCKIT_JDK_URL  
+  mv $JROCKIT_JDK_FILE $CACHE_DIR/Oracle/software
+  
+  chmod 777 $CACHE_DIR/Oracle/software/$JROCKIT_JDK_FILE
+  ./Oracle/software/$JROCKIT_JDK_FILE -mode=silent -silent_xml=$COMPILE_BUILDPACK_DIR/config/silentForJRockit.xml
+  
+  export JAVA_HOME=/app/Oracle/jrockit-jdk1.6.0_20
+  export JRE_HOME=${JAVA_HOME}/jre
+  export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib
+  export PATH=${JAVA_HOME}/bin:$PATH
+  echo " install of jrockit done"
+else
+  echo "-----> jrockit already present"
+fi
+
+# install WebLogic
+WEBLOGIC_FILE="wls1034_generic.jar"
+WEBLOGIC_PACKAGE="http://192.168.2.103:8001/buildpack/weblogic/wls1034_generic.jar" 
+if [ ! -d "${CACHE_DIR}/Oracle/Middleware_Home/wlserver_10.34" ]; then
+        mkdir -p $CACHE_DIR/Oracle/Middleware_Home/wlserver_10.34
+  echo -n "-----> Installing WebLogic1034 ${WEBLOGIC_FILE}..."
+  echo "Fetching ${WEBLOGIC_FILE} @ ${WEBLOGIC_PACKAGE}"
+  wget $WEBLOGIC_PACKAGE 
+  mv $WEBLOGIC_FILE $CACHE_DIR/Oracle/software
+  chmod 777 $CACHE_DIR/Oracle/software/$WEBLOGIC_FILE
+  java -Xmx1024m -jar $CACHE_DIR/Oracle/software/$WEBLOGIC_FILE -mode=silent -silent_xml=$COMPILE_BUILDPACK_DIR/config/silentForWebLogic.xml
+  
+  echo " install of WebLogic1034 done"
+else
+  echo "-----> WebLogic1034 already present"
+fi
+
+#set up WebLogic
+
+
+
+#deploy war：https://github.com/tchenData/buildpack-tomcat/blob/master/bin/compile
+
+
+echo "-----> Build SUCCESS"
